import './globals.css'
import { Shippori_Mincho } from 'next/font/google'

const shippori = Shippori_Mincho({
   subsets: ['latin'],
  //  weight: ['400','500','600'],
   weight: ['600'],
   variable: "--font-shippori",
  })

export const metadata = {
  title: '四條畷神社',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={shippori.variable}>{children}</body>
    </html>
  )
}
